### ISSUE TITLE
Error running mgn initalise lambda

### ISSUE THREAD

**Issue by txsutton** [aws-samples/aws-mgn-drs-init-automation#1]
I am running the mgn initialise lambda and get the following error

```
[ERROR] ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/var/task/index.py", line 51, in lambda_handler
    stagingTags = convert_list_to_dict(tags)
  File "/var/task/index.py", line 12, in convert_list_to_dict
    k,v = tag.split(":", 1)
```

**Comment by txsutton** [comment]
I am running mgn-initalise as a separate cloudformation (IAM roles was previously created via a separate terraform script) and got the above error - I suspect tags are not optional.

**Comment by txsutton** [comment]
Also pReplicationSecurityGroupIds is mandatory which is a bit strange as I have the option of setting pCreateReplicationSecurityGroup
